language: r

env:
  global:
    - secure: e1Z4qTEnkhJFpL9DpsvWMihLMwAcTeBgOrIsH6cLg49nboPIrni34dyTsP1zmYfgG8vwJjH+ATlSpGGStych2MOJbSaWFfn8QilpBXl0hTfkwFfx/3KXo4ouIUiASRPrKa4TrlT4b3Co4A8B4/THrrIDwLLgzAIXUAEwjrE9wNKeHTIK4lXwWwMdknh+jKEAYymjtFDH7EaGmaXtymmXt6e9X+6JWeuetqA85hQSKnqyq04ovcTz0GjdcY51dG/7qfiq9fOR5rs61m7VqnuGgVzDCnae1mcBHlZx/Bg7woACIbSfxLSXeW/pvvhZWG/fFGJjBTJDll6gej7jxLxmX2AgbVVRs77xHwOnDaI1y2vu6ONgx7VuPr+nEdd7mEeBKHkx36p88MQLrd/bUgQ2mLkU1cddi1UxWfOQye5rsJTKgESXRUedon6T3fg/nLq5/AhqVacffUDnUSbXPDk1SjyPHk6GQ8kzs4WkzLVKGLNPaGFlOuQ4C7ILwaXm1Bt2UJRhp5bLPw3XFuFPMD+qTRB7kpek/WQubWGwI0JQ34fdU7T1q2lW/wj5Km80Daa6lHITX6auh7eFrAhAQooZt+C7FVr1Z1lQxgV7oFclhzu4EtDJVAO1ayTnhoB8AU85Ts3Rjltzq23bJ8t4MhBWHX/QZTJpQX+RtF34oaZzikQ="

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh