--- 
title: "Principle of Machine Learning"
site: bookdown::bookdown_site
description: "This is my notes and solutions to lab on the course 'DAT276x Principle of Machine Learning' "
documentclass: book
---

# About this notebook {-}

This is my notes and solutions to lab on the course [**DAT276x Principle of Machine Learning: R Edition**](https://www.edx.org/course/principles-of-machine-learning-r-edition-2)

## Course Overview {-}

**1. Introduction to Machine Learning**

- High Level Data Science Process
  - High Level Process
- Overview of Machine Learning with K-Means Classifiers
  - Overview of Machine Learning with K-Means Classifiers
  - Demo of K-Means Classification
  
**2. Exploring Data**

- Exploratory Data Analysis for Regression
  - Data Exploration
  - Data Visualization
  - Visualizing Distributions
  - Visualizing Data Relationships
  - Visualizing Categorical Relationships
  - Using Aesthetics to Visualize High Dimensions
  - Visualizing High Dimensional Relationships
- Exploratory Data Analysis for Classification
  - Visualizing for Classification
  - Frequency Tables

**3. Cleaning and Preparing Data**

- Data Preparation and Cleaning
  - Data Preparation
  - Duplicates
  - Missing Values
  - Errors and Outliers
  - Scaling
  - Splitting
  - Summary
  - Finding and Treating Missing Data
  - Finding and Treating Duplicates
  - Scaling Data
- Feature Engineering
  - Overview of Feature Engineering
  - Transforming Features
  - Interaction Terms
  - Summary
  - Feature Engineering

**4. Getting Started with Supervised Learning**

- Regression
  - Introduction to Linear Regression
  - Multiple Linear Regression
  - Basics of ML with R
  - Evaluating Regression Models
  - Demo of Evaluating Regression
  - Models with Categorical Variables
- Classification
  - Introduction to Classification
  - Loss Function for Classification
  - Statistical Learning Theory for Supervised Learning
  - Logistic Regression
  - Maximum Likelihood Perspective
  - Evaluating Classifiers
  - ROC Curves
  - ROC Curve Algorithms
  - Classification Models
  - Demo of Classifier Evaluation
  - Imbalanced Data
  - Approaches for Addressing Imbalanced Data

**5. Improving Model Performance**

- Principles of Model Improvement
  - Improving Models
  - Regularization
  - Performing Regularization
  - Interpreting Features
  - Features Selection
- Techniques for Improving Models
  - Sweeping Parameters
  - Cross Validation
  - Nested Cross Validation
  - Model Selection and Cross Validation
- Dimensionality Reduction
  - Overview of Dimensionality Reduction
  - Principal Component Analysis

**6. Machine Learning Algorithms**

- Introduction to Decision Trees
  - Decision Trees
  - What is Information
- Ensemble Methods
  - Boosting
  - AdaBoost
  - Coordinate Descent
  - Decision Forests
- Neural Networks
  - Introduction to Neural Networks
  - Backpropagation
- Support Vector Machines (SVMs)
  - Introduction to SVMs
  - Kernels for SVMs
- Bayes Theorem
  - Theory of Naive Bayes Models

**7. Unsupervised Learning**

- Clustering
  - Introduction to Clustering
  - K-Means Clustering
  - Hierachical Clustering
  - Evaluating Clustering Models

**8 Final Exam**

- Introduction
- About the Data
- Data Exploration
- Challenge 2: Classification
- Classification - Grading
- Challenge 3: Regression
- Regression Grading

---

## Lab Overview {-}

This course includes labs that you can use to gain hands-on experience of building data science solutions. The labs are graded, and you will be required to answer questions after each lab to verify that you have completed them successfully.

### Programming Languages Used in this Course {-}

Many of the labs involve writing code in R. This course does not attempt to teach you exhaustive programming skills and syntax in these languages, so any experience you may already have in either language will be useful. However, the labs and demonstrations will provide you with the code you need to perform the data science operations described in this course, even if you have no prior experience, and there are references to resources that will help you work with these languages.

### Platform Requirements {-}

To execute the labs for this course you will need a computer meeting the following minimum requirements

- At least `10GB` of free disk space.
- At least `8 GB` of RAM.
- Running Windows, MAC OS X, or Linux.

### Installing Software for the Labs {-}

If you do not already have an environment capable of running a Jupyter notebook with an R kernel, follow the steps below.

1. **Anaconda stack**: Installing Anaconda is one of the easiest ways to install Jupyter notebooks. Download the Python 3.X version for your operating system from the [Anaconda download page](https://www.anaconda.com/download/).
2. **R**: Download and install the latest version of R from the [Comprehensive R Archive Network](https://cran.r-project.org/)
3. **Jupyter R Kernel**: In order to run R in Jupyter you must download the [Jupyter IRkernel](https://irkernel.github.io/installation/). Follow the directions carefully. You can run a simple R session required for this installation by starting R and using the console. If this is the **first time you have installed R** you will need to run the command options(repos = "https://CRAN.R-project.org") before you can install R packages, including the IRKernel. Important note for MAC users Note the warning that you must run the commands in step 2 in a command console, not from R
4. **Lab Materials From the Course Repository**: You can download the Zip file with the course lab materials from [the course Github repository](https://github.com/MicrosoftLearning/Principles-of-Machine-Learning-R). Click on the Clone or download tab, and selected Download Zip. If you have Git installed, you can clone this repository.
5. **Install R packages**: You can install the R packages you will require for the labs by executing the code in the **Setup** notebook.
Note: If you experience continual Jupyter kernel restarts, you may need to reinstall the R Rcpp package by executing the install.packages("Rcpp") command from the R console

